"""initial schema

Revision ID: 6787b62c58e3
Revises: 
Create Date: 2026-10-07 01:02:34.543618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6787b62c58e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_owner', sa.String(length=255), nullable=False),
    sa.Column('github_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.Column('primary_language', sa.String(length=64), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_owner', 'github_name', name='uq_repo_owner_name')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('target_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('analyzer_versions_json', sa.JSON(), nullable=True),
    sa.Column('fingerprint_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('ix_scans_repository_created', ['repository_id', 'created_at'], unique=False)

    op.create_table('analyzer_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('analyzer', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('raw_artifact_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_inventory', schema=None) as batch_op:
        batch_op.create_index('ix_file_inventory_scan_path', ['scan_id', 'path'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('analyzer', sa.String(length=64), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_scan_rule', ['scan_id', 'rule_id'], unique=False)
        batch_op.create_index('ix_findings_scan_severity', ['scan_id', 'severity'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('from_path', sa.String(length=512), nullable=False),
    sa.Column('to_path', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_edges_scan', ['scan_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.String(length=255), nullable=True),
    sa.Column('effort', sa.String(length=1), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_recommendations_scan_rank', ['scan_id', 'rank'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'category', name='uq_score_scan_category')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_finding', ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_finding')

    op.drop_table('evidence')
    op.drop_table('scores')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_recommendations_scan_rank')

    op.drop_table('recommendations')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_edges_scan')

    op.drop_table('graph_edges')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_scan_severity')
        batch_op.drop_index('ix_findings_scan_rule')

    op.drop_table('findings')
    with op.batch_alter_table('file_inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_file_inventory_scan_path')

    op.drop_table('file_inventory')
    op.drop_table('analyzer_runs')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('ix_scans_repository_created')

    op.drop_table('scans')
    op.drop_table('repositories')
    # ### end Alembic commands ###
